#!/usr/bin/env python3
"""
Generate Report -- reads JSON report files and produces a human-readable
markdown summary suitable for pasting into GitHub Issues or PRs.

Usage:
    python scripts/generate_report.py profile_results.json
    python scripts/generate_report.py benchmark_results.json --output report.md
    python scripts/generate_report.py results1.json results2.json
"""

import argparse
import json
import sys
from pathlib import Path


def load_report(path: str) -> dict:
    """Load a JSON report file."""
    with open(path) as f:
        return json.load(f)


def format_finding(finding: dict, index: int) -> str:
    """Format a single finding as markdown."""
    severity = finding.get("severity", "info").upper()
    title = finding.get("title", "Untitled")
    desc = finding.get("description", "")
    rec = finding.get("recommendation", "")

    lines = [f"{index}. **[{severity}]** {title}"]
    if desc:
        lines.append(f"   {desc}")
    if rec:
        lines.append(f"   - Recommendation: {rec}")

    evidence = finding.get("evidence", {})
    if evidence:
        lines.append(f"   - Evidence: `{json.dumps(evidence, separators=(',', ':'))[:200]}`")

    return "\n".join(lines)


def format_latency(label: str, profile: dict) -> str:
    """Format a latency profile as a table row."""
    return (
        f"| {label:<30} | {profile.get('mean_ms', 0):>8.1f} | "
        f"{profile.get('median_ms', 0):>8.1f} | {profile.get('p95_ms', 0):>8.1f} | "
        f"{profile.get('p99_ms', 0):>8.1f} | {profile.get('count', 0):>6} |"
    )


def generate_markdown(reports: list[tuple[str, dict]]) -> str:
    """Generate a markdown report from one or more JSON reports."""
    lines = ["# MCP Lab Test Report", ""]

    for source, report in reports:
        suite = report.get("suite", "unknown")
        lines.append(f"## {suite}")
        lines.append(f"Source: `{source}`")
        lines.append("")

        # Summary
        summary = report.get("summary", {})
        if summary:
            lines.append("### Summary")
            lines.append(f"- Total findings: {summary.get('total_findings', 0)}")
            lines.append(f"- Critical: {summary.get('critical', 0)}")
            lines.append(f"- Warnings: {summary.get('warnings', 0)}")
            lines.append(f"- Info: {summary.get('info', 0)}")
            lines.append("")

        # Findings
        findings = report.get("findings", [])
        if findings:
            lines.append("### Findings")
            lines.append("")
            for i, f in enumerate(findings, 1):
                lines.append(format_finding(f, i))
                lines.append("")

        # Latency
        latency = report.get("latency", {})
        if latency:
            lines.append("### Latency Profiles")
            lines.append("")
            lines.append(f"| {'Label':<30} | {'Mean':>8} | {'P50':>8} | {'P95':>8} | {'P99':>8} | {'n':>6} |")
            lines.append(f"|{'-'*32}|{'-'*10}|{'-'*10}|{'-'*10}|{'-'*10}|{'-'*8}|")
            for label, profile in latency.items():
                lines.append(format_latency(label, profile))
            lines.append("")

        lines.append("---")
        lines.append("")

    lines.append("Generated by [MCP Lab](https://github.com/your-org/mcp-lab)")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="Generate markdown report from MCP Lab JSON results"
    )
    parser.add_argument("reports", nargs="+", help="JSON report files to process")
    parser.add_argument("--output", default=None, help="Output markdown file path")

    args = parser.parse_args()

    reports = []
    for path in args.reports:
        try:
            report = load_report(path)
            reports.append((path, report))
        except (FileNotFoundError, json.JSONDecodeError) as e:
            print(f"Warning: Could not load {path}: {e}", file=sys.stderr)

    if not reports:
        print("No valid reports to process.", file=sys.stderr)
        sys.exit(1)

    markdown = generate_markdown(reports)

    if args.output:
        Path(args.output).write_text(markdown)
        print(f"Report written to: {args.output}")
    else:
        print(markdown)


if __name__ == "__main__":
    main()
